### ISSUE TITLE
Add REST endpoint for clearing State

### ISSUE THREAD

**Issue by myedibleenso** [lum-ai/odinson#44]
## Problem
Currently there isn't a way to clear the State from the UI or REST API

## Tasks
- [ ] Add endpoint in backend to clear the State
- [ ] Add endpoint to OpenAPI spec
- [ ] Wire up with UI (ex. `clear-state` -> `/api/clear-state`)

**Comment by kwalcock** [comment]
Why is the state hanging around needing to be cleared?
